version: '3'

services:
  store:
    build:
      context: .
      dockerfile: Dockerfile.store
    working_dir: /github.com/davidterranova/homework
    ports:
      - "5000:5000"
    command: -bind-address=:5000
