FROM golang:1.16 as builder
WORKDIR /go/src/github.com/davidterranova/homework
COPY . .
RUN make build-store

FROM alpine as runner
RUN apk --no-cache add ca-certificates
COPY --from=builder /go/src/github.com/davidterranova/homework/ports-store /ports-store
ENTRYPOINT ["/ports-store"]